/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.github.scaronthesky.eternalwinterwars.model.units;

import java.util.UUID;

import com.github.scaronthesky.eternalwinterwars.model.players.Player;
import com.github.scaronthesky.eternalwinterwars.model.units.bluntarmamentbehaviour.BluntArmamentBehaviour;
import com.github.scaronthesky.eternalwinterwars.model.units.bluntweaponbehaviours.BluntWeaponBehaviour;
import com.github.scaronthesky.eternalwinterwars.model.units.costbehaviours.CostBehaviour;
import com.github.scaronthesky.eternalwinterwars.model.units.healthbehaviours.HealthBehaviour;
import com.github.scaronthesky.eternalwinterwars.model.units.movementbehaviours.UnitMovementBehaviour;
import com.github.scaronthesky.eternalwinterwars.model.units.piercingarmamentbehaviours.PiercingArmamentBehaviour;
import com.github.scaronthesky.eternalwinterwars.model.units.piercingweaponbehaviours.PiercingWeaponBehaviour;
import com.github.scaronthesky.eternalwinterwars.model.units.sightbehaviours.UnitSightBehaviour;

public class UnitBuilder {

	private Unit unit;

	public UnitBuilder() {

	}

	public UnitBuilder withUUID(UUID uuid) {
		this.unit.setUuid(uuid);
		return this;
	}

	public UnitBuilder withOwner(Player player) {
		this.unit.setOwner(player);
		return this;
	}

	public UnitBuilder withHealthBehaviour(HealthBehaviour healthBehaviour){
		this.unit.setInitialHealth(healthBehaviour);
		return this;
	}

	public UnitBuilder withMovementBehaviour(UnitMovementBehaviour movementBehaviour) {
		this.unit.setMovementBehaviour(movementBehaviour);
		return this;
	}

	public UnitBuilder withPiercingWeaponBehaviour(
			PiercingWeaponBehaviour piercingWeaponBehaviour) {
		this.unit.setPiercingWeaponBehaviour(piercingWeaponBehaviour);
		return this;
	}

	public UnitBuilder withPiercingArmamentBehaviour(
			PiercingArmamentBehaviour piercingArmamentBehaviour) {
		this.unit.setPiercingArmamentBehaviour(piercingArmamentBehaviour);
		return this;
	}

	public UnitBuilder withBluntWeaponBehaviour(
			BluntWeaponBehaviour bluntWeaponBehaviour) {
		this.unit.setBluntWeaponBehaviour(bluntWeaponBehaviour);
		return this;
	}

	public UnitBuilder withBluntArmamentBehaviour(
			BluntArmamentBehaviour bluntArmamentBehaviour) {
		this.unit.setBluntArmamentBehaviour(bluntArmamentBehaviour);
		return this;
	}

	public UnitBuilder withSightBehaviour(UnitSightBehaviour sightBehaviour) {
		this.unit.setSightBehaviour(sightBehaviour);
		return this;
	}

	public UnitBuilder withCostBehaviour(CostBehaviour costBehaviour) {
		this.unit.setCostBehaviour(costBehaviour);
		return this;
	}

	public Unit build() {
		return this.unit;
	}

}
